# Use OpenJDK 8 as the base image
FROM openjdk:8-jdk-alpine
  
  # Set the working directory inside the container
WORKDIR /app
  
  # Copy the compiled JAR file into the container
COPY target/job-board-app.jar app.jar
  
  # Expose the application's port (change if needed)
EXPOSE 8080
  
  # Run the application
CMD ["java", "-jar", "app.jar"]
